### ISSUE TITLE
on mac

### ISSUE THREAD

**Issue by mengchaoheng** [aditya00j/ulogviewer#1]
ulogviewer
Reading /Users/mch/Proj/ulogviewer/log_8_2021-5-20-11-52-08.ulg... Creating output directory /Users/mch/Proj/ulogviewer/Temporary/143909
Traceback (most recent call last):
  File "/usr/local/bin/ulog2csv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pyulog/ulog2csv.py", line 40, in main
    os.mkdir(args.output)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mch/Proj/ulogviewer/Temporary/143909'
done
Index exceeds the number of array elements. Index must not exceed 0.

Error in ulogviewer>listMessages_Callback (line 219)
this_message = contents{get(hObject,'Value')};

Error in ulogviewer>buttonSelect_Callback (line 145)
    listMessages_Callback(handles.listMessages, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ulogviewer (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ulogviewer('buttonSelect_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by mengchaoheng** [comment]
ulogviewer
Reading /Users/mch/Proj/ulogviewer/log_8_2021-5-20-11-52-08.ulg... Creating output directory /Users/mch/Proj/ulogviewer/Temporary/143909
Traceback (most recent call last):
  File "/usr/local/bin/ulog2csv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pyulog/ulog2csv.py", line 40, in main
    os.mkdir(args.output)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mch/Proj/ulogviewer/Temporary/143909'
done
Index exceeds the number of array elements. Index must not exceed 0.

Error in ulogviewer>listMessages_Callback (line 219)
this_message = contents{get(hObject,'Value')};

Error in ulogviewer>buttonSelect_Callback (line 145)
    listMessages_Callback(handles.listMessages, eventdata, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in ulogviewer (line 42)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)ulogviewer('buttonSelect_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by mengchaoheng** [comment]
@aditya00j
